export const inputFormElements = [
  {
    name: "PanNumber",
    placeholder: "Enter pan number",
    label: "PanNumber",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 12,
    required: "Required field",
    pattern: {
      value: /^([a-zA-Z]){5}([0-9]){4}([a-zA-Z]){1}?$/i,
      message: "Invalid Pan Number",
    },
  },
  {
    name: "AdhaarNumber",
    placeholder: "Enter Adhaar Number",
    label: "Adhaar Number",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 12,
    required: "Required field",
    pattern: {
      value: /^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$/i,
      message: "Invalid Adhaar Number",
    },
  },
  {
    name: "GSTNumber",
    placeholder: "Enter GSTNumber",
    label: "GSTNumber",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 12,
    required: "Required field",
    pattern: {
      value: /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/i,
      message: "Invalid GST Number",
    },
  },
  {
    name: "AccNumber",
    type: "number",
    placeholder: "Enter AccNumber",
    label: "AccNumber",
    variant: "outlined",
    fullWidth: true,
    required: "Required field",
    xs: 12,
    sm: 12,
  },
  {
    name: "ConfirmAccNumber",
    type: "number",
    placeholder: "Confirm AccNumber",
    label: "ConfirmAccNumber",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 12,
    required: "Required field",
  },
  {
    name: "IFSCCode",
    placeholder: "Enter IFSC Code",
    label: "IFSC Code",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 12,
    required: "Required field",
  },
  {
    name: "street",
    placeholder: "Enter street",
    label: "Street",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    required: "Required field",
  },
  {
    name: "city",
    placeholder: "Enter city name",
    label: "City",
    variant: "outlined",
    fullWidth: true,
    required: "Required field",
    xs: 12,
    sm: 6,
  },
  {
    name: "state",
    placeholder: "Enter state",
    label: "State",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    required: "Required field",
  },
  {
    name: "pincode",
    placeholder: "Enter pincode number",
    label: "Pincode",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    required: "Required field",
    pattern: {
      value: /^[1-9]{1}[0-9]{2}\\s{0, 1}[0-9]{3}$/i,
      message: "Invalid Pan Number",
    },
  },
];
